language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - xvfb
script:
  - npm run lint
  - npm run test
cache:
  directories:
    - node_modules
after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start